-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Improved Promotions Data v1.59
-- Author: Arstahd
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



----------   UNIT UPDATES   ----------


--  ALL SIEGE:  Remove move and shoot penalty
DELETE FROM TypeTags WHERE Type='ABILITY_NO_MOVE_AND_SHOOT' AND Tag='CLASS_SIEGE_SETUP';

--  ALL SIEGE:  Lower Bombard Strength by 5
UPDATE Units SET Bombard=Bombard-5 WHERE PromotionClass='PROMOTION_CLASS_SIEGE';
--  Add +1 move as compensation for Khmer Domrey since they can Move and Shoot normally
UPDATE Units SET BaseMoves=BaseMoves+1 WHERE UnitType='UNIT_KHMER_DOMREY';


--  ALL NAVAL CARRIER:  Add ranged combat and anti-air, increase melee combat, sight range, and cost
UPDATE Units SET Cost=Cost*1.25, Maintenance=Maintenance+1, BaseSightRange=BaseSightRange+1, Combat=Combat+5, RangedCombat=Combat, Range=3, AntiAirCombat= 90 WHERE PromotionClass='PROMOTION_CLASS_NAVAL_CARRIER';




----------   PROMOTION UPDATES   ----------


-- Create HIDDEN promotion class
INSERT INTO Types (Type, Kind) VALUES ('PROMOTION_CLASS_HIDDEN', 'KIND_PROMOTION_CLASS');

INSERT INTO UnitPromotionClasses (PromotionClassType, Name) VALUES ('PROMOTION_CLASS_HIDDEN', 'LOC_PROMOTION_CLASS_HIDDEN_NAME');


-- Remove original promotions
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_RECON';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_MELEE';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_RANGED';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_SIEGE';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_ANTI_CAVALRY';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_LIGHT_CAVALRY';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_HEAVY_CAVALRY';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_NAVAL_MELEE';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_NAVAL_RANGED';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_NAVAL_RAIDER';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_NAVAL_CARRIER';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_AIR_FIGHTER';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_AIR_BOMBER';
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_MONK';

UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE UnitPromotionType='PROMOTION_INDULGENCE_VENDOR';




--  Create new promotions
INSERT OR REPLACE INTO Types (Type, Kind) VALUES 
-----   RECON   -----
		('PROMOTION_SPECIAL_FORCES_II', 'KIND_PROMOTION'),
		('PROMOTION_SPECIAL_FORCES', 'KIND_PROMOTION'),
		('PROMOTION_RECON_1', 'KIND_PROMOTION'),
		('PROMOTION_RECON_2', 'KIND_PROMOTION'),
		('PROMOTION_RECON_3', 'KIND_PROMOTION'),
		('PROMOTION_RECON_4', 'KIND_PROMOTION'),
		('PROMOTION_GUIDE', 'KIND_PROMOTION'),
		('PROMOTION_SHEPHERD', 'KIND_PROMOTION'),

-----   MELEE   -----
		('PROMOTION_AMBIDEXTROUS_MELEE', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_MELEE_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_MELEE', 'KIND_PROMOTION'),
		('PROMOTION_MELEE_1', 'KIND_PROMOTION'),
		('PROMOTION_MELEE_2', 'KIND_PROMOTION'),
		('PROMOTION_MELEE_3', 'KIND_PROMOTION'),
		('PROMOTION_MELEE_4', 'KIND_PROMOTION'),

-----   RANGED   -----
		('PROMOTION_AMBIDEXTROUS_RANGED', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_RANGED_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_RANGED', 'KIND_PROMOTION'),
		('PROMOTION_RANGED_1', 'KIND_PROMOTION'),
		('PROMOTION_RANGED_2', 'KIND_PROMOTION'),
		('PROMOTION_RANGED_3', 'KIND_PROMOTION'),
		('PROMOTION_RANGED_4', 'KIND_PROMOTION'),
		('PROMOTION_SIDE_ARMS', 'KIND_PROMOTION'),

-----   SIEGE   -----
		('PROMOTION_AMBIDEXTROUS_SIEGE', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_SIEGE_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_SIEGE', 'KIND_PROMOTION'),
		('PROMOTION_SIEGE_1', 'KIND_PROMOTION'),
		('PROMOTION_SIEGE_2', 'KIND_PROMOTION'),
		('PROMOTION_SIEGE_3', 'KIND_PROMOTION'),
		('PROMOTION_SIEGE_4', 'KIND_PROMOTION'),
		('PROMOTION_RESUPPLY', 'KIND_PROMOTION'),

-----   ANTI CAVALRY   -----
		('PROMOTION_AMBIDEXTROUS_SPEAR', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_SPEAR_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_SPEAR', 'KIND_PROMOTION'),
		('PROMOTION_SPEAR_1', 'KIND_PROMOTION'),
		('PROMOTION_SPEAR_2', 'KIND_PROMOTION'),
		('PROMOTION_SPEAR_3', 'KIND_PROMOTION'),
		('PROMOTION_SPEAR_4', 'KIND_PROMOTION'),
		('PROMOTION_MARCH', 'KIND_PROMOTION'),
		('PROMOTION_CLOSE_RANKS', 'KIND_PROMOTION'),
		('PROMOTION_TO_THE_LAST', 'KIND_PROMOTION'),

-----   LIGHT CAVALRY   -----
		('PROMOTION_AMBIDEXTROUS_LIGHT', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_LIGHT_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_LIGHT', 'KIND_PROMOTION'),
		('PROMOTION_LIGHT_1', 'KIND_PROMOTION'),
		('PROMOTION_LIGHT_2', 'KIND_PROMOTION'),
		('PROMOTION_LIGHT_3', 'KIND_PROMOTION'),
		('PROMOTION_LIGHT_4', 'KIND_PROMOTION'),
		('PROMOTION_HIT_AND_RUN', 'KIND_PROMOTION'),
		('PROMOTION_EVASIVE_TARGET', 'KIND_PROMOTION'),

-----   HEAVY CAVALRY   -----
		('PROMOTION_AMBIDEXTROUS_HEAVY', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_HEAVY_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_HEAVY', 'KIND_PROMOTION'),
		('PROMOTION_HEAVY_1', 'KIND_PROMOTION'),
		('PROMOTION_HEAVY_2', 'KIND_PROMOTION'),
		('PROMOTION_HEAVY_3', 'KIND_PROMOTION'),
		('PROMOTION_HEAVY_4', 'KIND_PROMOTION'),
		('PROMOTION_URBAN_ASSAULT', 'KIND_PROMOTION'),
		('PROMOTION_RELENTLESS', 'KIND_PROMOTION'),

-----   NAVAL MELEE   -----
		('PROMOTION_AMBIDEXTROUS_NAVAL_MELEE', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_NAVAL_MELEE_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_NAVAL_MELEE', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_MELEE_1', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_MELEE_2', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_MELEE_3', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_MELEE_4', 'KIND_PROMOTION'),
		('PROMOTION_ONSLAUGHT', 'KIND_PROMOTION'),

-----   NAVAL RANGED   -----
		('PROMOTION_AMBIDEXTROUS_NAVAL_RANGED', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_NAVAL_RANGED_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_NAVAL_RANGED', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_RANGED_1', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_RANGED_2', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_RANGED_3', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_RANGED_4', 'KIND_PROMOTION'),
		('PROMOTION_RANGEFINDING', 'KIND_PROMOTION'),

-----   NAVAL RAIDER   -----
		('PROMOTION_AMBIDEXTROUS_NAVAL_RAIDER', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_NAVAL_RAIDER_II', 'KIND_PROMOTION'),
        ('PROMOTION_SPECIAL_NAVAL_RAIDER', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_RAIDER_1', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_RAIDER_2', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_RAIDER_3', 'KIND_PROMOTION'),
		('PROMOTION_NAVAL_RAIDER_4', 'KIND_PROMOTION'),
		('PROMOTION_QUICK_FIRING', 'KIND_PROMOTION'),
		('PROMOTION_PREDATOR', 'KIND_PROMOTION'),

-----   NAVAL CARRIER   -----
		('PROMOTION_MISSILE_ARRAY', 'KIND_PROMOTION'),
		('PROMOTION_COMPARTMENTED_HULL', 'KIND_PROMOTION'),

-----   AIR FIGHTER   -----
		('PROMOTION_AIR_FIGHTER_1', 'KIND_PROMOTION'),
		('PROMOTION_AIR_FIGHTER_2', 'KIND_PROMOTION'),
		('PROMOTION_AIR_FIGHTER_3', 'KIND_PROMOTION'),

-----   AIR BOMBER   -----
		('PROMOTION_AIR_BOMBER_1', 'KIND_PROMOTION'),
		('PROMOTION_AIR_BOMBER_2', 'KIND_PROMOTION'),
		('PROMOTION_AIR_BOMBER_3', 'KIND_PROMOTION'),

-----   MONK   -----
		('PROMOTION_MONK_IRON_FISTS', 'KIND_PROMOTION'),
		('PROMOTION_MONK_ENDURING_DRAGON', 'KIND_PROMOTION'),
		('PROMOTION_MONK_ZEALOTS', 'KIND_PROMOTION'),

-----   APOSTLE   -----
		('PROMOTION_EXEMPLAR', 'KIND_PROMOTION');



INSERT OR REPLACE INTO UnitPromotions (UnitPromotionType, Name, Description, Level, Column, PromotionClass) VALUES 
-----   RECON   -----
		('PROMOTION_RECON_4', 'LOC_PROMOTION_AMBUSH_4_NAME', 'LOC_PROMOTION_AMBUSH_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_RECON'),		
		('PROMOTION_RECON_3', 'LOC_PROMOTION_AMBUSH_3_NAME', 'LOC_PROMOTION_AMBUSH_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_RECON'),		
		('PROMOTION_RECON_2', 'LOC_PROMOTION_AMBUSH_2_NAME', 'LOC_PROMOTION_AMBUSH_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_RECON'),		
		('PROMOTION_RECON_1', 'LOC_PROMOTION_AMBUSH_1_NAME', 'LOC_PROMOTION_AMBUSH_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_RECON'),
		
		('PROMOTION_SPECIAL_FORCES_II', 'LOC_PROMOTION_SPECIAL_FORCES_II_NAME', 'LOC_PROMOTION_SPECIAL_FORCES_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_RECON'),
		('PROMOTION_SPECIAL_FORCES', 'LOC_PROMOTION_SPECIAL_FORCES_NAME', 'LOC_PROMOTION_SPECIAL_FORCES_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_RECON'),
		('PROMOTION_GUERRILLA', 'LOC_PROMOTION_GUERRILLA_NAME', 'LOC_PROMOTION_GUERRILLA_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_RECON'),
		('PROMOTION_SHEPHERD', 'LOC_PROMOTION_SHEPHERD_NAME', 'LOC_PROMOTION_SHEPHERD_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_RECON'),

		('PROMOTION_SENTRY', 'LOC_PROMOTION_SENTRY_NAME', 'LOC_PROMOTION_SENTRY_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_RECON'),
		('PROMOTION_GUIDE', 'LOC_PROMOTION_GUIDE_NAME', 'LOC_PROMOTION_GUIDE_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_RECON'),
		('PROMOTION_ALPINE', 'LOC_PROMOTION_ALPINE_NAME', 'LOC_PROMOTION_ALPINE_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_RECON'),
		('PROMOTION_RANGER', 'LOC_PROMOTION_RANGER_NAME', 'LOC_PROMOTION_RANGER_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_RECON'),

-----   MELEE   -----
		('PROMOTION_MELEE_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_MELEE_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_MELEE_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_MELEE_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_MELEE'),

		('PROMOTION_SPECIAL_MELEE_II', 'LOC_PROMOTION_SPECIAL_MELEE_II_NAME', 'LOC_PROMOTION_SPECIAL_MELEE_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_SPECIAL_MELEE', 'LOC_PROMOTION_SPECIAL_MELEE_NAME', 'LOC_PROMOTION_SPECIAL_MELEE_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_ELITE_GUARD', 'LOC_PROMOTION_ELITE_GUARD_NAME', 'LOC_PROMOTION_ELITE_GUARD_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_AMBIDEXTROUS_MELEE', 'LOC_PROMOTION_AMBIDEXTROUS_MELEE_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_MELEE_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_MELEE'),

		('PROMOTION_AMPHIBIOUS', 'LOC_PROMOTION_AMPHIBIOUS_NAME', 'LOC_PROMOTION_AMPHIBIOUS_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_URBAN_WARFARE', 'LOC_PROMOTION_URBAN_WARFARE_NAME', 'LOC_PROMOTION_URBAN_WARFARE_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_TORTOISE', 'LOC_PROMOTION_TORTOISE_NAME', 'LOC_PROMOTION_TORTOISE_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_MELEE'),
		('PROMOTION_BATTLECRY', 'LOC_PROMOTION_BATTLECRY_NAME', 'LOC_PROMOTION_BATTLECRY_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_MELEE'),

-----   RANGED   -----
		('PROMOTION_RANGED_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_RANGED_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_RANGED_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_RANGED_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_RANGED'),

		('PROMOTION_SPECIAL_RANGED_II', 'LOC_PROMOTION_SPECIAL_RANGED_II_NAME', 'LOC_PROMOTION_SPECIAL_RANGED_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_SPECIAL_RANGED', 'LOC_PROMOTION_SPECIAL_RANGED_NAME', 'LOC_PROMOTION_SPECIAL_RANGED_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_EXPERT_MARKSMAN', 'LOC_PROMOTION_EXPERT_MARKSMAN_NAME', 'LOC_PROMOTION_EXPERT_MARKSMAN_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_AMBIDEXTROUS_RANGED', 'LOC_PROMOTION_AMBIDEXTROUS_RANGED_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_RANGED_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_RANGED'),

		('PROMOTION_INCENDIARIES', 'LOC_PROMOTION_INCENDIARIES_NAME', 'LOC_PROMOTION_INCENDIARIES_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_GARRISON', 'LOC_PROMOTION_GARRISON_NAME', 'LOC_PROMOTION_GARRISON_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_SIDE_ARMS', 'LOC_PROMOTION_SIDE_ARMS_NAME', 'LOC_PROMOTION_SIDE_ARMS_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_RANGED'),
		('PROMOTION_VOLLEY', 'LOC_PROMOTION_VOLLEY_NAME', 'LOC_PROMOTION_VOLLEY_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_RANGED'),


-----   SIEGE   -----
		('PROMOTION_SIEGE_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_SIEGE_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_SIEGE_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_SIEGE_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_SIEGE'),

		('PROMOTION_SPECIAL_SIEGE_II', 'LOC_PROMOTION_SPECIAL_SIEGE_II_NAME', 'LOC_PROMOTION_SPECIAL_SIEGE_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_SPECIAL_SIEGE', 'LOC_PROMOTION_SPECIAL_SIEGE_NAME', 'LOC_PROMOTION_SPECIAL_SIEGE_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_FORWARD_OBSERVERS', 'LOC_PROMOTION_FORWARD_OBSERVERS_NAME', 'LOC_PROMOTION_FORWARD_OBSERVERS_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_AMBIDEXTROUS_SIEGE', 'LOC_PROMOTION_AMBIDEXTROUS_SIEGE_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_SIEGE_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_SIEGE'),

		('PROMOTION_RESUPPLY', 'LOC_PROMOTION_RESUPPLY_NAME', 'LOC_PROMOTION_RESUPPLY_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_SHRAPNEL', 'LOC_PROMOTION_SHRAPNEL_NAME', 'LOC_PROMOTION_SHRAPNEL_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_CREW_WEAPONS', 'LOC_PROMOTION_CREW_WEAPONS_NAME', 'LOC_PROMOTION_CREW_WEAPONS_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_SIEGE'),
		('PROMOTION_SHELLS', 'LOC_PROMOTION_SHELLS_NAME', 'LOC_PROMOTION_SHELLS_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_SIEGE'),

-----   ANTI CAVALRY   -----
		('PROMOTION_SPEAR_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_SPEAR_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_SPEAR_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_SPEAR_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_ANTI_CAVALRY'),

		('PROMOTION_SPECIAL_SPEAR_II', 'LOC_PROMOTION_SPECIAL_SPEAR_II_NAME', 'LOC_PROMOTION_SPECIAL_SPEAR_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_SPECIAL_SPEAR', 'LOC_PROMOTION_SPECIAL_SPEAR_NAME', 'LOC_PROMOTION_SPECIAL_SPEAR_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_REDEPLOY', 'LOC_PROMOTION_REDEPLOY_NAME', 'LOC_PROMOTION_REDEPLOY_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_AMBIDEXTROUS_SPEAR', 'LOC_PROMOTION_AMBIDEXTROUS_SPEAR_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_SPEAR_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_ANTI_CAVALRY'),

		('PROMOTION_MARCH', 'LOC_PROMOTION_MARCH_NAME', 'LOC_PROMOTION_MARCH_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_ECHELON', 'LOC_PROMOTION_ECHELON_NAME', 'LOC_PROMOTION_ECHELON_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_CLOSE_RANKS', 'LOC_PROMOTION_CLOSE_RANKS_NAME', 'LOC_PROMOTION_CLOSE_RANKS_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_ANTI_CAVALRY'),
		('PROMOTION_TO_THE_LAST', 'LOC_PROMOTION_TO_THE_LAST_NAME', 'LOC_PROMOTION_TO_THE_LAST_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_ANTI_CAVALRY'),

-----   LIGHT CAVALRY   -----
		('PROMOTION_LIGHT_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_LIGHT_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_LIGHT_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_LIGHT_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_LIGHT_CAVALRY'),

		('PROMOTION_SPECIAL_LIGHT_II', 'LOC_PROMOTION_SPECIAL_LIGHT_II_NAME', 'LOC_PROMOTION_SPECIAL_LIGHT_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_SPECIAL_LIGHT', 'LOC_PROMOTION_SPECIAL_LIGHT_NAME', 'LOC_PROMOTION_SPECIAL_LIGHT_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_HIT_AND_RUN', 'LOC_PROMOTION_HIT_AND_RUN_NAME', 'LOC_PROMOTION_HIT_AND_RUN_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_AMBIDEXTROUS_LIGHT', 'LOC_PROMOTION_AMBIDEXTROUS_LIGHT_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_LIGHT_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_LIGHT_CAVALRY'),

		('PROMOTION_ESCORT_MOBILITY', 'LOC_PROMOTION_ESCORT_MOBILITY_NAME', 'LOC_PROMOTION_ESCORT_MOBILITY_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_COURSERS', 'LOC_PROMOTION_COURSERS_NAME', 'LOC_PROMOTION_COURSERS_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_EVASIVE_TARGET', 'LOC_PROMOTION_EVASIVE_TARGET_NAME', 'LOC_PROMOTION_EVASIVE_TARGET_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_LIGHT_CAVALRY'),
		('PROMOTION_DOUBLE_ENVELOPMENT', 'LOC_PROMOTION_DOUBLE_ENVELOPMENT_NAME', 'LOC_PROMOTION_DOUBLE_ENVELOPMENT_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_LIGHT_CAVALRY'),

-----   HEAVY CAVALRY   -----
		('PROMOTION_HEAVY_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_HEAVY_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_HEAVY_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_HEAVY_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_HEAVY_CAVALRY'),

		('PROMOTION_SPECIAL_HEAVY_II', 'LOC_PROMOTION_SPECIAL_HEAVY_II_NAME', 'LOC_PROMOTION_SPECIAL_HEAVY_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_SPECIAL_HEAVY', 'LOC_PROMOTION_SPECIAL_HEAVY_NAME', 'LOC_PROMOTION_SPECIAL_HEAVY_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_BREAKTHROUGH', 'LOC_PROMOTION_BREAKTHROUGH_NAME', 'LOC_PROMOTION_BREAKTHROUGH_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_AMBIDEXTROUS_HEAVY', 'LOC_PROMOTION_AMBIDEXTROUS_HEAVY_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_HEAVY_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_HEAVY_CAVALRY'),

		('PROMOTION_ROUT', 'LOC_PROMOTION_ROUT_NAME', 'LOC_PROMOTION_ROUT_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_URBAN_ASSAULT', 'LOC_PROMOTION_URBAN_ASSAULT_NAME', 'LOC_PROMOTION_URBAN_ASSAULT_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_BARDING', 'LOC_PROMOTION_BARDING_NAME', 'LOC_PROMOTION_BARDING_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_HEAVY_CAVALRY'),
		('PROMOTION_RELENTLESS', 'LOC_PROMOTION_RELENTLESS_NAME', 'LOC_PROMOTION_RELENTLESS_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_HEAVY_CAVALRY'),

-----   NAVAL MELEE   -----
		('PROMOTION_NAVAL_MELEE_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_NAVAL_MELEE_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_NAVAL_MELEE_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_NAVAL_MELEE_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_NAVAL_MELEE'),

		('PROMOTION_SPECIAL_NAVAL_MELEE_II', 'LOC_PROMOTION_SPECIAL_NAVAL_MELEE_II_NAME', 'LOC_PROMOTION_SPECIAL_NAVAL_MELEE_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_SPECIAL_NAVAL_MELEE', 'LOC_PROMOTION_SPECIAL_NAVAL_MELEE_NAME', 'LOC_PROMOTION_SPECIAL_NAVAL_MELEE_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_ONSLAUGHT', 'LOC_PROMOTION_ONSLAUGHT_NAME', 'LOC_PROMOTION_ONSLAUGHT_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_AMBIDEXTROUS_NAVAL_MELEE', 'LOC_PROMOTION_AMBIDEXTROUS_NAVAL_MELEE_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_NAVAL_MELEE_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_NAVAL_MELEE'),

		('PROMOTION_AUXILIARY_SHIPS', 'LOC_PROMOTION_AUXILIARY_SHIPS_NAME', 'LOC_PROMOTION_AUXILIARY_SHIPS_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_HELMSMAN', 'LOC_PROMOTION_HELMSMAN_NAME', 'LOC_PROMOTION_HELMSMAN_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_REINFORCED_HULL', 'LOC_PROMOTION_REINFORCED_HULL_NAME', 'LOC_PROMOTION_REINFORCED_HULL_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_NAVAL_MELEE'),
		('PROMOTION_EMBOLON', 'LOC_PROMOTION_EMBOLON_NAME', 'LOC_PROMOTION_EMBOLON_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_NAVAL_MELEE'),

-----   NAVAL RANGED   -----
		('PROMOTION_NAVAL_RANGED_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_NAVAL_RANGED_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_NAVAL_RANGED_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_NAVAL_RANGED_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_NAVAL_RANGED'),

		('PROMOTION_SPECIAL_NAVAL_RANGED_II', 'LOC_PROMOTION_SPECIAL_NAVAL_RANGED_II_NAME', 'LOC_PROMOTION_SPECIAL_NAVAL_RANGED_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_SPECIAL_NAVAL_RANGED', 'LOC_PROMOTION_SPECIAL_NAVAL_RANGED_NAME', 'LOC_PROMOTION_SPECIAL_NAVAL_RANGED_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_RANGEFINDING', 'LOC_PROMOTION_RANGEFINDING_NAME', 'LOC_PROMOTION_RANGEFINDING_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_AMBIDEXTROUS_NAVAL_RANGED', 'LOC_PROMOTION_AMBIDEXTROUS_NAVAL_RANGED_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_NAVAL_RANGED_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_NAVAL_RANGED'),

		('PROMOTION_SUPPLY_FLEET', 'LOC_PROMOTION_SUPPLY_FLEET_NAME', 'LOC_PROMOTION_SUPPLY_FLEET_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_PREPARATORY_FIRE', 'LOC_PROMOTION_PREPARATORY_FIRE_NAME', 'LOC_PROMOTION_PREPARATORY_FIRE_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_BOMBARDMENT', 'LOC_PROMOTION_BOMBARDMENT_NAME', 'LOC_PROMOTION_BOMBARDMENT_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_NAVAL_RANGED'),
		('PROMOTION_LINE_OF_BATTLE', 'LOC_PROMOTION_LINE_OF_BATTLE_NAME', 'LOC_PROMOTION_LINE_OF_BATTLE_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_NAVAL_RANGED'),

-----   NAVAL RAIDER   -----
		('PROMOTION_NAVAL_RAIDER_4', 'LOC_PROMOTION_VETERAN_4_NAME', 'LOC_PROMOTION_VETERAN_4_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_NAVAL_RAIDER_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_NAVAL_RAIDER_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_NAVAL_RAIDER_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_NAVAL_RAIDER'),

		('PROMOTION_SPECIAL_NAVAL_RAIDER_II', 'LOC_PROMOTION_SPECIAL_NAVAL_RAIDER_II_NAME', 'LOC_PROMOTION_SPECIAL_NAVAL_RAIDER_II_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_SPECIAL_NAVAL_RAIDER', 'LOC_PROMOTION_SPECIAL_NAVAL_RAIDER_NAME', 'LOC_PROMOTION_SPECIAL_NAVAL_RAIDER_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_QUICK_FIRING', 'LOC_PROMOTION_QUICK_FIRING_NAME', 'LOC_PROMOTION_QUICK_FIRING_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_AMBIDEXTROUS_NAVAL_RAIDER', 'LOC_PROMOTION_AMBIDEXTROUS_NAVAL_RAIDER_NAME', 'LOC_PROMOTION_AMBIDEXTROUS_NAVAL_RAIDER_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_NAVAL_RAIDER'),

		('PROMOTION_BOARDING', 'LOC_PROMOTION_BOARDING_NAME', 'LOC_PROMOTION_BOARDING_DESCRIPTION', 1, 5, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_SWIFT_KEEL', 'LOC_PROMOTION_SWIFT_KEEL_NAME', 'LOC_PROMOTION_SWIFT_KEEL_DESCRIPTION', 2, 5, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_SILENT_RUNNING', 'LOC_PROMOTION_SILENT_RUNNING_NAME', 'LOC_PROMOTION_SILENT_RUNNING_DESCRIPTION', 3, 5, 'PROMOTION_CLASS_NAVAL_RAIDER'),
		('PROMOTION_PREDATOR', 'LOC_PROMOTION_PREDATOR_NAME', 'LOC_PROMOTION_PREDATOR_DESCRIPTION', 4, 5, 'PROMOTION_CLASS_NAVAL_RAIDER'),

-----   NAVAL CARRIER   -----
		('PROMOTION_SUPER_CARRIER', 'LOC_PROMOTION_SUPER_CARRIER_NAME', 'LOC_PROMOTION_SUPER_CARRIER_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_NAVAL_CARRIER'),
		('PROMOTION_FOLDING_WINGS', 'LOC_PROMOTION_FOLDING_WINGS_NAME', 'LOC_PROMOTION_FOLDING_WINGS_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_NAVAL_CARRIER'),
		('PROMOTION_HANGAR_DECK', 'LOC_PROMOTION_HANGAR_DECK_NAME', 'LOC_PROMOTION_HANGAR_DECK_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_NAVAL_CARRIER'),
		('PROMOTION_FLIGHT_DECK', 'LOC_PROMOTION_FLIGHT_DECK_NAME', 'LOC_PROMOTION_FLIGHT_DECK_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_NAVAL_CARRIER'),

		('PROMOTION_DECK_CREWS', 'LOC_PROMOTION_DECK_CREWS_NAME', 'LOC_PROMOTION_DECK_CREWS_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_NAVAL_CARRIER'),
		('PROMOTION_ADVANCED_ENGINES', 'LOC_PROMOTION_ADVANCED_ENGINES_NAME', 'LOC_PROMOTION_ADVANCED_ENGINES_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_NAVAL_CARRIER'),
		('PROMOTION_MISSILE_ARRAY', 'LOC_PROMOTION_MISSILE_ARRAY_NAME', 'LOC_PROMOTION_MISSILE_ARRAY_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_NAVAL_CARRIER'),
		('PROMOTION_COMPARTMENTED_HULL', 'LOC_PROMOTION_COMPARTMENTED_HULL_NAME', 'LOC_PROMOTION_COMPARTMENTED_HULL_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_NAVAL_CARRIER'),

-----   AIR FIGHTER   -----
		('PROMOTION_DROP_TANKS', 'LOC_PROMOTION_DROP_TANKS_NAME', 'LOC_PROMOTION_DROP_TANKS_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_AIR_FIGHTER'),
		('PROMOTION_AIR_FIGHTER_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_AIR_FIGHTER'),
		('PROMOTION_AIR_FIGHTER_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_AIR_FIGHTER'),
		('PROMOTION_AIR_FIGHTER_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_AIR_FIGHTER'),

		('PROMOTION_GROUND_CREWS', 'LOC_PROMOTION_GROUND_CREWS_NAME', 'LOC_PROMOTION_GROUND_CREWS_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_AIR_FIGHTER'),
		('PROMOTION_TANK_BUSTER', 'LOC_PROMOTION_TANK_BUSTER_NAME', 'LOC_PROMOTION_TANK_BUSTER_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_AIR_FIGHTER'),
		('PROMOTION_STRAFE', 'LOC_PROMOTION_STRAFE_NAME', 'LOC_PROMOTION_STRAFE_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_AIR_FIGHTER'),
		('PROMOTION_INTERCEPTOR', 'LOC_PROMOTION_INTERCEPTOR_NAME', 'LOC_PROMOTION_INTERCEPTOR_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_AIR_FIGHTER'),

-----   AIR BOMBER   -----
		('PROMOTION_SUPERFORTRESS', 'LOC_PROMOTION_SUPERFORTRESS_NAME', 'LOC_PROMOTION_SUPERFORTRESS_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_AIR_BOMBER'),
		('PROMOTION_AIR_BOMBER_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_AIR_BOMBER'),
		('PROMOTION_AIR_BOMBER_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_AIR_BOMBER'),
		('PROMOTION_AIR_BOMBER_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_AIR_BOMBER'),

		('PROMOTION_TACTICAL_MAINTENANCE', 'LOC_PROMOTION_TACTICAL_MAINTENANCE_NAME', 'LOC_PROMOTION_TACTICAL_MAINTENANCE_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_AIR_BOMBER'),
		('PROMOTION_TORPEDO_BOMBER', 'LOC_PROMOTION_TORPEDO_BOMBER_NAME', 'LOC_PROMOTION_TORPEDO_BOMBER_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_AIR_BOMBER'),
		('PROMOTION_CLOSE_AIR_SUPPORT', 'LOC_PROMOTION_CLOSE_AIR_SUPPORT_NAME', 'LOC_PROMOTION_CLOSE_AIR_SUPPORT_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_AIR_BOMBER'),
		('PROMOTION_EVASIVE_MANEUVERS', 'LOC_PROMOTION_EVASIVE_MANEUVERS_NAME', 'LOC_PROMOTION_EVASIVE_MANEUVERS_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_AIR_BOMBER'),

-----   MONK   -----
		('PROMOTION_MONK_ZEALOTS', 'LOC_PROMOTION_MONK_ZEALOTS_NAME', 'LOC_PROMOTION_MONK_ZEALOTS_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_MONK'),
		('PROMOTION_MONK_DISCIPLES', 'LOC_PROMOTION_MONK_DISCIPLES_NAME', 'LOC_PROMOTION_MONK_DISCIPLES_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_MONK'),

		('PROMOTION_MONK_EXPLODING_PALMS', 'LOC_PROMOTION_MONK_EXPLODING_PALMS_NAME', 'LOC_PROMOTION_MONK_EXPLODING_PALMS_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_MONK'),
		('PROMOTION_MONK_IRON_FISTS', 'LOC_PROMOTION_MONK_IRON_FISTS_NAME', 'LOC_PROMOTION_MONK_IRON_FISTS_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_MONK'),

		('PROMOTION_MONK_ENDURING_DRAGON', 'LOC_PROMOTION_MONK_ENDURING_DRAGON_NAME', 'LOC_PROMOTION_MONK_ENDURING_DRAGON_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_MONK'),
		('PROMOTION_MONK_DANCING_CRANE', 'LOC_PROMOTION_MONK_DANCING_CRANE_NAME', 'LOC_PROMOTION_MONK_DANCING_CRANE_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_MONK'),

		('PROMOTION_MONK_SWEEPING_WIND', 'LOC_PROMOTION_MONK_SWEEPING_WIND_NAME', 'LOC_PROMOTION_MONK_SWEEPING_WIND_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_MONK'),
		('PROMOTION_MONK_SHADOW_STRIKE', 'LOC_PROMOTION_MONK_SHADOW_STRIKE_NAME', 'LOC_PROMOTION_MONK_SHADOW_STRIKE_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_MONK'),

-----   APOSTLE   -----
		('PROMOTION_EXEMPLAR', 'LOC_PROMOTION_EXEMPLAR_NAME', 'LOC_PROMOTION_EXEMPLAR_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_APOSTLE');



INSERT OR REPLACE INTO UnitPromotionModifiers (UnitPromotionType, ModifierId) VALUES 
-----   RECON   -----
		('PROMOTION_RECON_4', 'AMBUSH_4_COMBAT_BONUS'),
		('PROMOTION_RECON_3', 'AMBUSH_3_COMBAT_BONUS'),
		('PROMOTION_RECON_2', 'AMBUSH_2_COMBAT_BONUS'),
		('PROMOTION_RECON_1', 'AMBUSH_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_FORCES_II', 'FORWARD_OBSERVERS_BONUS_RANGE'),
		('PROMOTION_SPECIAL_FORCES_II', 'EXPERT_MARKSMAN_ADDITIONAL_ATTACK'),
		('PROMOTION_SPECIAL_FORCES_II', 'BATTLECRY_ATTACK_BONUS'),
		('PROMOTION_SPECIAL_FORCES_II', 'INCREASE_HEAL_RATE_15'),

		('PROMOTION_SPECIAL_FORCES', 'MOD_MOVE_AFTER_ATTACKING'), -- FADE_BONUS_MOVE_AFTER_ATTACKING 
		('PROMOTION_SPECIAL_FORCES', 'HEAL_AFTER_ACTION'),
		('PROMOTION_SPECIAL_FORCES', 'SIDE_ARMS_DEFENSE_BONUS'),
		('PROMOTION_SPECIAL_FORCES', 'INCREASE_HEAL_RATE_10'),
		
		('PROMOTION_GUERRILLA', 'LONG_RANGE_BONUS_RANGE'),
		('PROMOTION_GUERRILLA', 'CAMOUFLAGE_STEALTH'),
		('PROMOTION_GUERRILLA', 'TORTOISE_DEFENSE_BONUS'),
		('PROMOTION_GUERRILLA', 'INCREASE_HEAL_RATE_5'),

		('PROMOTION_SHEPHERD', 'DANCING_CRANE_BONUS_MOVEMENT'),
		('PROMOTION_SHEPHERD', 'HELMSMAN_BONUS_WATER_MOVEMENT'),
		('PROMOTION_SHEPHERD', 'ESCORT_MOBILITY_SHARED_MOVEMENT'),

		('PROMOTION_SENTRY', 'SPYGLASS_BONUS_SIGHT'),
    	('PROMOTION_SENTRY', 'RELENTLESS_STRENGTH_REDUCTION'),
		('PROMOTION_SENTRY', 'SENTRY_COMBAT_BONUS'),

		('PROMOTION_GUIDE', 'AMPHIBIOUS_BONUS_IGNORE_RIVERS'),
		('PROMOTION_GUIDE', 'AMPHIBIOUS_BONUS_IGNORE_SHORES'),
		('PROMOTION_GUIDE', 'AQUATIC_BONUS_SEA_MOVEMENT'),

		('PROMOTION_ALPINE', 'ALPINE_IGNORE_HILLS_MOVEMENT_PENALTY'),
		('PROMOTION_ALPINE', 'ALPINE_SEE_THROUGH_TERRAIN'), --('ALPINE_SEE_THROUGH_TERRAIN', 'CanSee', 1),
		('PROMOTION_ALPINE', 'COMMANDO_BONUS_IGNORE_CLIFF_WALLS'),

		('PROMOTION_RANGER', 'RANGER_IGNORE_FOREST_MOVEMENT_PENALTY'),
		('PROMOTION_RANGER', 'SENTRY_SEE_THROUGH_FEATURES'),
		('PROMOTION_RANGER', 'CREW_WEAPONS_DEFENSE_BONUS'),

-----   MELEE   -----
		('PROMOTION_MELEE_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_MELEE_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_MELEE_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_MELEE_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_MELEE_II', 'HELMSMAN_BONUS_WATER_MOVEMENT'),
		('PROMOTION_SPECIAL_MELEE_II', 'ELITE_GUARD_ADDITIONAL_ATTACK'),
		('PROMOTION_SPECIAL_MELEE_II', 'INCREASE_HEAL_RATE_15'),
		
		('PROMOTION_SPECIAL_MELEE', 'FORWARD_OBSERVERS_BONUS_RANGE'),
		('PROMOTION_SPECIAL_MELEE', 'INCREASE_HEAL_RATE_10'),
		('PROMOTION_SPECIAL_MELEE', 'MOD_MOVE_AFTER_ATTACKING'),
		
		('PROMOTION_ELITE_GUARD', 'RELENTLESS_STRENGTH_REDUCTION'),
		('PROMOTION_ELITE_GUARD', 'HEAL_AFTER_ACTION'),
		('PROMOTION_ELITE_GUARD', 'CREW_WEAPONS_DEFENSE_BONUS'),
		
		('PROMOTION_AMBIDEXTROUS_MELEE', 'VOLLEY_ATTACK_BONUS'),
		('PROMOTION_AMBIDEXTROUS_MELEE', 'SIDE_ARMS_DEFENSE_BONUS'),

		('PROMOTION_AMPHIBIOUS', 'AMPHIBIOUS_BONUS_IGNORE_SHORES'),
		('PROMOTION_AMPHIBIOUS', 'AMPHIBIOUS_BONUS_IGNORE_RIVERS'),
		('PROMOTION_AMPHIBIOUS', 'AMPHIBIOUS_BONUS_SEA_MOVEMENT'),
		('PROMOTION_AMPHIBIOUS', 'COMMANDO_BONUS_IGNORE_CLIFF_WALLS'),
		('PROMOTION_URBAN_WARFARE', 'URBAN_WARFARE_BONUS'),
		('PROMOTION_TORTOISE', 'TORTOISE_DEFENSE_BONUS'),
		('PROMOTION_BATTLECRY', 'BATTLECRY_ATTACK_BONUS'),

-----   RANGED   ----- 
		('PROMOTION_RANGED_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_RANGED_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_RANGED_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_RANGED_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_RANGED_II', 'INCREASE_HEAL_RATE_15'),
		('PROMOTION_SPECIAL_RANGED_II', 'EXPERT_MARKSMAN_ADDITIONAL_ATTACK'),
		
		('PROMOTION_SPECIAL_RANGED', 'HEAL_AFTER_ACTION'),
		('PROMOTION_SPECIAL_RANGED', 'FORWARD_OBSERVERS_BONUS_RANGE'),
		('PROMOTION_SPECIAL_RANGED', 'MOD_MOVE_AFTER_ATTACKING'),
		
		('PROMOTION_EXPERT_MARKSMAN', 'RELENTLESS_STRENGTH_REDUCTION'),
		('PROMOTION_EXPERT_MARKSMAN', 'HELMSMAN_BONUS_WATER_MOVEMENT'),
		('PROMOTION_EXPERT_MARKSMAN', 'CREW_WEAPONS_DEFENSE_BONUS'),
		
		('PROMOTION_AMBIDEXTROUS_RANGED', 'DOUBLE_ENVELOPMENT_ATTACK_BONUS'),
		('PROMOTION_AMBIDEXTROUS_RANGED', 'SIDE_ARMS_DEFENSE_BONUS'),       

		('PROMOTION_INCENDIARIES', 'INCENDIARIES_BONUS_VS_DISTRICT_DEFENSES'),
		('PROMOTION_GARRISON', 'GARRISON_BONUS_DISTRICTS'),
		('PROMOTION_SIDE_ARMS', 'SIDE_ARMS_DEFENSE_BONUS'),
		('PROMOTION_VOLLEY', 'VOLLEY_ATTACK_BONUS'),

-----   SIEGE   ----- 
		('PROMOTION_SIEGE_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_SIEGE_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_SIEGE_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_SIEGE_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_SIEGE_II', 'INCREASE_HEAL_RATE_15'),
		('PROMOTION_SPECIAL_SIEGE_II', 'EXPERT_MARKSMAN_ADDITIONAL_ATTACK'),
		
		('PROMOTION_SPECIAL_SIEGE', 'FORWARD_OBSERVERS_BONUS_RANGE'),
		('PROMOTION_SPECIAL_SIEGE', 'MOD_MOVE_AFTER_ATTACKING'),
		('PROMOTION_SPECIAL_SIEGE', 'HEAL_AFTER_ACTION'),
		
		('PROMOTION_FORWARD_OBSERVERS', 'RELENTLESS_STRENGTH_REDUCTION'),
		('PROMOTION_FORWARD_OBSERVERS', 'HELMSMAN_BONUS_WATER_MOVEMENT'),
		('PROMOTION_FORWARD_OBSERVERS', 'GARRISON_BONUS_DISTRICTS'),
		
		('PROMOTION_AMBIDEXTROUS_SIEGE', 'VOLLEY_ATTACK_BONUS'),
		('PROMOTION_AMBIDEXTROUS_SIEGE', 'SIDE_ARMS_DEFENSE_BONUS'),

		('PROMOTION_RESUPPLY', 'INCREASE_HEAL_RATE_10'),
		('PROMOTION_SHRAPNEL', 'BOMBARD_BONUS_VS_UNITS'),
		('PROMOTION_CREW_WEAPONS', 'CREW_WEAPONS_DEFENSE_BONUS'),
		('PROMOTION_SHELLS', 'SHELLS_BONUS_VS_DISTRICTS'),

-----   ANTI CAVALRY   ----- 
		('PROMOTION_SPEAR_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_SPEAR_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_SPEAR_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_SPEAR_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_SPEAR_II', 'AMPHIBIOUS_BONUS_SEA_MOVEMENT'),
		('PROMOTION_SPECIAL_SPEAR', 'MOD_MOVE_AFTER_ATTACKING'),
		('PROMOTION_REDEPLOY', 'ELITE_GUARD_ADDITIONAL_ATTACK'),
        ('PROMOTION_AMBIDEXTROUS_SPEAR', 'ALPINE_SEE_THROUGH_TERRAIN'),

		('PROMOTION_MARCH', 'HEAL_AFTER_ACTION'),
		('PROMOTION_ECHELON', 'ECHELON_ADDITIONAL_CAVALRY_BONUS'),
		('PROMOTION_CLOSE_RANKS', 'CLOSE_RANKS_DEFENSE_BONUS'),
		('PROMOTION_TO_THE_LAST', 'RELENTLESS_STRENGTH_REDUCTION'),

-----   LIGHT CAVALRY   ----- 
		('PROMOTION_LIGHT_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_LIGHT_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_LIGHT_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_LIGHT_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_LIGHT_II', 'PURSUIT_BONUS_MOVEMENT'),
		('PROMOTION_SPECIAL_LIGHT', 'MOD_MOVE_AFTER_ATTACKING'),
		('PROMOTION_HIT_AND_RUN', 'HEAL_AFTER_ACTION'),
		('PROMOTION_AMBIDEXTROUS_LIGHT', 'DEPREDATION_BONUS_ADVANCED_PILLAGING'),

		('PROMOTION_ESCORT_MOBILITY', 'ESCORT_MOBILITY_SHARED_MOVEMENT'),
		--('PROMOTION_ESCORT_MOBILITY', 'PURSUIT_BONUS_MOVEMENT'),
		('PROMOTION_COURSERS', 'COURSERS_BONUS_VS_RANGED_SIEGE'),
		('PROMOTION_EVASIVE_TARGET', 'EVASIVE_TARGET_DEFENSE_BONUS'),
		('PROMOTION_DOUBLE_ENVELOPMENT', 'DOUBLE_ENVELOPMENT_ATTACK_BONUS'),

-----   HEAVY CAVALRY   ----- PROMOTION_AMBIDEXTROUS_HEAVY
		('PROMOTION_HEAVY_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_HEAVY_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_HEAVY_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_HEAVY_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_HEAVY_II', 'AMPHIBIOUS_BONUS_SEA_MOVEMENT'),
		('PROMOTION_SPECIAL_HEAVY', 'MOD_MOVE_AFTER_ATTACKING'),
		('PROMOTION_BREAKTHROUGH', 'BREAKTHROUGH_ADDITIONAL_ATTACK'),
        ('PROMOTION_AMBIDEXTROUS_HEAVY', 'ALPINE_SEE_THROUGH_TERRAIN'),

		('PROMOTION_ROUT', 'HUSSAR_FORCE_RETREAT'),
		('PROMOTION_URBAN_ASSAULT', 'URBAN_ASSAULT_BONUS'),
		('PROMOTION_BARDING', 'BARDING_DEFENSE_BONUS'),
		('PROMOTION_RELENTLESS', 'RELENTLESS_STRENGTH_REDUCTION'),

-----   NAVAL MELEE   ----- 
		('PROMOTION_NAVAL_MELEE_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_NAVAL_MELEE_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_NAVAL_MELEE_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_NAVAL_MELEE_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_NAVAL_MELEE_II', 'HELMSMAN_BONUS_WATER_MOVEMENT'),
		('PROMOTION_SPECIAL_NAVAL_MELEE', 'MOD_MOVE_AFTER_ATTACKING'),
		('PROMOTION_ONSLAUGHT', 'BREAKTHROUGH_ADDITIONAL_ATTACK'),
		('PROMOTION_AMBIDEXTROUS_NAVAL_MELEE', 'INCREASE_HEAL_RATE_5'),

		('PROMOTION_AUXILIARY_SHIPS', 'AUXILIARY_SHIPS_NEUTRAL_TERRITORY_HEAL'),
		('PROMOTION_AUXILIARY_SHIPS', 'AUXILIARY_SHIPS_ENEMY_TERRITORY_HEAL'),
		--('PROMOTION_HELMSMAN', 'HELMSMAN_BONUS_WATER_MOVEMENT'),
		('PROMOTION_HELMSMAN', 'RUTTER_SIGHT_BONUS'),
		('PROMOTION_REINFORCED_HULL', 'REINFORCED_HULL_DEFENSE_BONUS'),
		('PROMOTION_EMBOLON', 'EMBOLON_BONUS_VS_NAVAL'),

-----   NAVAL RANGED   ----- 
		('PROMOTION_NAVAL_RANGED_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_NAVAL_RANGED_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_NAVAL_RANGED_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_NAVAL_RANGED_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_NAVAL_RANGED_II', 'SENTRY_SEE_THROUGH_FEATURES'),
		('PROMOTION_SPECIAL_NAVAL_RANGED', 'COINCIDENCE_RANGEFINDING_BONUS_RANGE'),
		('PROMOTION_RANGEFINDING', 'SENTRY_SEE_THROUGH_FEATURES'),
		('PROMOTION_RANGEFINDING', 'ALPINE_SEE_THROUGH_TERRAIN'),
		('PROMOTION_AMBIDEXTROUS_NAVAL_RANGED', 'INCREASE_HEAL_RATE_5'),

		('PROMOTION_SUPPLY_FLEET', 'SUPPLY_FLEET_NEUTRAL_TERRITORY_HEAL'),
		('PROMOTION_SUPPLY_FLEET', 'SUPPLY_FLEET_ENEMY_TERRITORY_HEAL'),
		('PROMOTION_PREPARATORY_FIRE', 'PREPARATORY_FIRE_BONUS_VS_LAND'),
		('PROMOTION_BOMBARDMENT', 'BOMBARDMENT_BONUS_VS_DISTRICT_DEFENSES'),
		('PROMOTION_LINE_OF_BATTLE', 'LINE_OF_BATTLE_BONUS_VS_NAVAL'),

-----   NAVAL RAIDER   ----- 
		('PROMOTION_NAVAL_RAIDER_4', 'VETERAN_4_COMBAT_BONUS'),
		('PROMOTION_NAVAL_RAIDER_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_NAVAL_RAIDER_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_NAVAL_RAIDER_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_SPECIAL_NAVAL_RAIDER_II', 'REINFORCED_HULL_DEFENSE_BONUS'),
		('PROMOTION_SPECIAL_NAVAL_RAIDER', 'SWIFT_KEEL_BONUS_MOVEMENT'),
		('PROMOTION_QUICK_FIRING', 'WOLFPACK_ADDITIONAL_ATTACK'),
		('PROMOTION_AMBIDEXTROUS_NAVAL_RAIDER', 'BOARDING_GOLD_FROM_NAVAL_VICTORY'),

		('PROMOTION_BOARDING', 'HEAL_FROM_COMBAT'),
		('PROMOTION_SWIFT_KEEL', 'OBSERVATION_INCREASED_SIGHT_RANGE'),
		('PROMOTION_SILENT_RUNNING', 'SILENT_RUNNING_MOVE_AFTER_ATTACKING'),
		('PROMOTION_PREDATOR', 'PREDATOR_BONUS_VS_NAVAL'),

-----   NAVAL CARRIER   -----
		('PROMOTION_SUPER_CARRIER', 'SUPER_CARRIER_COMBAT_BONUS'),
		('PROMOTION_FOLDING_WINGS', 'FOLDING_WINGS_BONUS_AIRCRAFT_SLOT'),
		('PROMOTION_HANGAR_DECK', 'HANGAR_DECK_BONUS_AIRCRAFT_SLOT'),
		('PROMOTION_FLIGHT_DECK', 'FLIGHT_DECK_BONUS_AIRCRAFT_SLOT'),

		('PROMOTION_DECK_CREWS', 'SUPER_CARRIER_NEUTRAL_TERRITORY_HEAL'),
		('PROMOTION_DECK_CREWS', 'SUPER_CARRIER_ENEMY_TERRITORY_HEAL'),
		('PROMOTION_DECK_CREWS', 'INCREASE_HEAL_RATE_5'),
		('PROMOTION_ADVANCED_ENGINES', 'ADVANCED_ENGINES_BONUS_MOVEMENT'),
		('PROMOTION_ADVANCED_ENGINES', 'SCOUT_PLANES_BONUS_SIGHT'),
		('PROMOTION_MISSILE_ARRAY', 'MISSILE_ARRAY_ATTACK_BONUS'),
		('PROMOTION_COMPARTMENTED_HULL', 'COMPARTMENTED_HULL_DEFENSE_BONUS'),

-----   AIR FIGHTER   -----
		('PROMOTION_DROP_TANKS', 'LONG_RANGE_ESCORT_BONUS_RANGE'),
		('PROMOTION_AIR_FIGHTER_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_AIR_FIGHTER_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_AIR_FIGHTER_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_GROUND_CREWS', 'GROUND_CREWS_BONUS_HEALTH'),
		('PROMOTION_TANK_BUSTER', 'TANK_BUSTER_BONUS_VS_CAVALRY'),
		('PROMOTION_TANK_BUSTER', 'TANK_BUSTER_BONUS_VS_DISTRICTS'),
		('PROMOTION_STRAFE', 'STRAFE_BONUS_VS_NONCAVALRY'),
		('PROMOTION_INTERCEPTOR', 'DOGFIGHTING_BONUS_VS_FIGHTERS'),
		('PROMOTION_INTERCEPTOR', 'INTERCEPTOR_BONUS_VS_BOMBERS'),

-----   AIR BOMBER   -----
		('PROMOTION_SUPERFORTRESS', 'SUPERFORTRESS_BONUS_ADVANCED_PILLAGING'),
		('PROMOTION_SUPERFORTRESS', 'LONG_RANGE_BONUS_RANGE'),
		('PROMOTION_AIR_BOMBER_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_AIR_BOMBER_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_AIR_BOMBER_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_TACTICAL_MAINTENANCE', 'TACTICAL_MAINTENANCE_HEAL_AFTER_ACTION'),
		('PROMOTION_TORPEDO_BOMBER', 'TORPEDO_BOMBER_BONUS_VS_NAVAL'),
		('PROMOTION_CLOSE_AIR_SUPPORT', 'CLOSE_AIR_SUPPORT_BONUS_VS_LAND'),
		('PROMOTION_EVASIVE_MANEUVERS', 'BOX_FORMATION_DEFENSE_BONUS_VS_FIGHTERS'),
		('PROMOTION_EVASIVE_MANEUVERS', 'EVASIVE_MANEUVERS_BONUS_VS_ANTIAIR'),

-----   MONK   -----
		('PROMOTION_MONK_DISCIPLES', 'DISCIPLES_LAND_VICTORY_SPREAD'),
		('PROMOTION_MONK_DISCIPLES', 'DISCIPLES_FAITH_FROM_COMBAT'),
		('PROMOTION_MONK_ZEALOTS', 'ZEALOTS_COMBAT_BONUS'),

		('PROMOTION_MONK_IRON_FISTS', 'IRON_FISTS_COMBAT_BONUS'),
		('PROMOTION_MONK_EXPLODING_PALMS', 'EXPLODING_PALMS_COMBAT_BONUS'),

		('PROMOTION_MONK_DANCING_CRANE', 'DANCING_CRANE_BONUS_MOVEMENT'),
--		('PROMOTION_MONK_DANCING_CRANE', 'DANCING_CRANE_DEFENSE_BONUS'),
		('PROMOTION_MONK_DANCING_CRANE', 'DANCING_CRANE_IGNORE_ZOC'),
		('PROMOTION_MONK_ENDURING_DRAGON', 'HEAL_AFTER_ACTION'),
		('PROMOTION_MONK_ENDURING_DRAGON', 'INCREASED_HEAL_RATE_5'),

		('PROMOTION_MONK_SHADOW_STRIKE', 'CAMOUFLAGE_STEALTH'),
		('PROMOTION_MONK_SHADOW_STRIKE', 'SHADOW_STRIKE_ATTACK_BONUS'),
		('PROMOTION_MONK_SWEEPING_WIND', 'SWEEPING_WIND_ADDITIONAL_ATTACK'),
		('PROMOTION_MONK_SWEEPING_WIND', 'MOD_MOVE_AFTER_ATTACKING'),

-----   APOSTLE   -----
		('PROMOTION_HEATHEN_CONVERSION', 'APOSTLE_SPREAD_CHARGE'),
		('PROMOTION_EXEMPLAR', 'APOSTLE_COMBAT_BOOST'),
		('PROMOTION_EXEMPLAR', 'APOSTLE_SPREAD_CHARGE');



INSERT OR REPLACE INTO UnitPromotionPrereqs (UnitPromotion, PrereqUnitPromotion) VALUES 
-----   RECON   -----
		('PROMOTION_RECON_1', 'PROMOTION_GUIDE'),
		('PROMOTION_RECON_2', 'PROMOTION_RECON_1'),
		('PROMOTION_RECON_3', 'PROMOTION_RECON_2'),
		('PROMOTION_RECON_4', 'PROMOTION_RECON_3'),

		('PROMOTION_SHEPHERD', 'PROMOTION_SENTRY'),
		('PROMOTION_GUERRILLA', 'PROMOTION_SHEPHERD'),
		('PROMOTION_SPECIAL_FORCES', 'PROMOTION_GUERRILLA'),
		('PROMOTION_SPECIAL_FORCES_II', 'PROMOTION_SPECIAL_FORCES'),

-----   MELEE   -----
		('PROMOTION_MELEE_2', 'PROMOTION_MELEE_1'),
		('PROMOTION_MELEE_3', 'PROMOTION_MELEE_2'),
		('PROMOTION_MELEE_4', 'PROMOTION_MELEE_3'),

		('PROMOTION_ELITE_GUARD', 'PROMOTION_AMBIDEXTROUS_MELEE'),
		('PROMOTION_SPECIAL_MELEE', 'PROMOTION_ELITE_GUARD'),
		('PROMOTION_SPECIAL_MELEE_II', 'PROMOTION_SPECIAL_MELEE'),

-----   RANGED   -----
		('PROMOTION_RANGED_2', 'PROMOTION_RANGED_1'),
		('PROMOTION_RANGED_3', 'PROMOTION_RANGED_2'),
		('PROMOTION_RANGED_4', 'PROMOTION_RANGED_3'),

		('PROMOTION_EXPERT_MARKSMAN', 'PROMOTION_AMBIDEXTROUS_RANGED'),
		('PROMOTION_SPECIAL_RANGED', 'PROMOTION_EXPERT_MARKSMAN'),
		('PROMOTION_SPECIAL_RANGED_II', 'PROMOTION_SPECIAL_RANGED'),

-----   SIEGE   -----
		('PROMOTION_SIEGE_2', 'PROMOTION_SIEGE_1'),
		('PROMOTION_SIEGE_3', 'PROMOTION_SIEGE_2'),
		('PROMOTION_SIEGE_4', 'PROMOTION_SIEGE_3'),

		('PROMOTION_FORWARD_OBSERVERS', 'PROMOTION_AMBIDEXTROUS_SIEGE'),
		('PROMOTION_SPECIAL_SIEGE', 'PROMOTION_FORWARD_OBSERVERS'),
		('PROMOTION_SPECIAL_SIEGE_II', 'PROMOTION_SPECIAL_SIEGE'),

-----   ANTI CAVALRY   -----
		('PROMOTION_SPEAR_2', 'PROMOTION_SPEAR_1'),
		('PROMOTION_SPEAR_3', 'PROMOTION_SPEAR_2'),
		('PROMOTION_SPEAR_4', 'PROMOTION_SPEAR_3'),

		('PROMOTION_REDEPLOY', 'PROMOTION_AMBIDEXTROUS_SPEAR'),
		('PROMOTION_SPECIAL_SPEAR', 'PROMOTION_REDEPLOY'),
		('PROMOTION_SPECIAL_SPEAR_II', 'PROMOTION_SPECIAL_SPEAR'),

-----   LIGHT CAVALRY   -----
		('PROMOTION_LIGHT_2', 'PROMOTION_LIGHT_1'),
		('PROMOTION_LIGHT_3', 'PROMOTION_LIGHT_2'),
		('PROMOTION_LIGHT_4', 'PROMOTION_LIGHT_3'),

		('PROMOTION_HIT_AND_RUN', 'PROMOTION_AMBIDEXTROUS_LIGHT'),
		('PROMOTION_SPECIAL_LIGHT', 'PROMOTION_HIT_AND_RUN'),
		('PROMOTION_SPECIAL_LIGHT_II', 'PROMOTION_SPECIAL_LIGHT'),

-----   HEAVY CAVALRY   -----
		('PROMOTION_HEAVY_2', 'PROMOTION_HEAVY_1'),
		('PROMOTION_HEAVY_3', 'PROMOTION_HEAVY_2'),
		('PROMOTION_HEAVY_4', 'PROMOTION_HEAVY_3'),

		('PROMOTION_BREAKTHROUGH', 'PROMOTION_AMBIDEXTROUS_HEAVY'),
		('PROMOTION_SPECIAL_HEAVY', 'PROMOTION_BREAKTHROUGH'),
		('PROMOTION_SPECIAL_HEAVY_II', 'PROMOTION_SPECIAL_HEAVY'),

-----   NAVAL MELEE   -----
		('PROMOTION_NAVAL_MELEE_2', 'PROMOTION_NAVAL_MELEE_1'),
		('PROMOTION_NAVAL_MELEE_3', 'PROMOTION_NAVAL_MELEE_2'),
		('PROMOTION_NAVAL_MELEE_4', 'PROMOTION_NAVAL_MELEE_3'),

		('PROMOTION_ONSLAUGHT', 'PROMOTION_AMBIDEXTROUS_NAVAL_MELEE'),
		('PROMOTION_SPECIAL_NAVAL_MELEE', 'PROMOTION_ONSLAUGHT'),
		('PROMOTION_SPECIAL_NAVAL_MELEE_II', 'PROMOTION_SPECIAL_NAVAL_MELEE'),

-----   NAVAL RANGED   -----
		('PROMOTION_NAVAL_RANGED_2', 'PROMOTION_NAVAL_RANGED_1'),
		('PROMOTION_NAVAL_RANGED_3', 'PROMOTION_NAVAL_RANGED_2'),
		('PROMOTION_NAVAL_RANGED_4', 'PROMOTION_NAVAL_RANGED_3'),

		('PROMOTION_RANGEFINDING', 'PROMOTION_AMBIDEXTROUS_NAVAL_RANGED'),
		('PROMOTION_SPECIAL_NAVAL_RANGED', 'PROMOTION_RANGEFINDING'),
		('PROMOTION_SPECIAL_NAVAL_RANGED_II', 'PROMOTION_SPECIAL_NAVAL_RANGED'),

-----   NAVAL RAIDER   -----
		('PROMOTION_NAVAL_RAIDER_2', 'PROMOTION_NAVAL_RAIDER_1'),
		('PROMOTION_NAVAL_RAIDER_3', 'PROMOTION_NAVAL_RAIDER_2'),
		('PROMOTION_NAVAL_RAIDER_4', 'PROMOTION_NAVAL_RAIDER_3'),

		('PROMOTION_QUICK_FIRING', 'PROMOTION_AMBIDEXTROUS_NAVAL_RAIDER'),
		('PROMOTION_SPECIAL_NAVAL_RAIDER', 'PROMOTION_QUICK_FIRING'),
		('PROMOTION_SPECIAL_NAVAL_RAIDER_II', 'PROMOTION_SPECIAL_NAVAL_RAIDER'),

-----   NAVAL CARRIER   -----
		('PROMOTION_HANGAR_DECK', 'PROMOTION_FLIGHT_DECK'),
		('PROMOTION_FOLDING_WINGS', 'PROMOTION_HANGAR_DECK'),
		('PROMOTION_SUPER_CARRIER', 'PROMOTION_FOLDING_WINGS'),

-----   AIR FIGHTER   -----
		('PROMOTION_AIR_FIGHTER_2', 'PROMOTION_AIR_FIGHTER_1'),
		('PROMOTION_AIR_FIGHTER_3', 'PROMOTION_AIR_FIGHTER_2'),
		('PROMOTION_DROP_TANKS', 'PROMOTION_AIR_FIGHTER_3'),

-----   AIR BOMBER   -----
		('PROMOTION_AIR_BOMBER_2', 'PROMOTION_AIR_BOMBER_1'),
		('PROMOTION_AIR_BOMBER_3', 'PROMOTION_AIR_BOMBER_2'),
		('PROMOTION_SUPERFORTRESS', 'PROMOTION_AIR_BOMBER_3'),

-----   MONK   -----
		('PROMOTION_MONK_ZEALOTS', 'PROMOTION_MONK_DISCIPLES'),
		('PROMOTION_MONK_EXPLODING_PALMS', 'PROMOTION_MONK_IRON_FISTS'),
		('PROMOTION_MONK_ENDURING_DRAGON', 'PROMOTION_MONK_DANCING_CRANE'),
		('PROMOTION_MONK_SWEEPING_WIND', 'PROMOTION_MONK_SHADOW_STRIKE');

-----   APOSTLE   -----



INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 
-----   RECON   -----
		('SENTRY_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'SENTRY_COMBAT_REQUIREMENTS'),
		('AQUATIC_BONUS_SEA_MOVEMENT', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 'UNIT_IS_ON_WATER_REQUIREMENTS'),
		('ALPINE_SEE_THROUGH_TERRAIN', 'MODIFIER_PLAYER_UNIT_ADJUST_SEE_THROUGH_TERRAIN', NULL),

-----   MELEE   -----
		('AMPHIBIOUS_BONUS_SEA_MOVEMENT', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 'UNIT_IS_ON_WATER_REQUIREMENTS'),
		('TORTOISE_DEFENSE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'CREW_WEAPONS_REQUIREMENTS'),
		('BATTLECRY_ATTACK_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'UNIT_IS_ATTACKING_REQUIREMENTS'),

-----   RANGED   -----
		('SIDE_ARMS_DEFENSE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'CREW_WEAPONS_REQUIREMENTS'),
		('VOLLEY_ATTACK_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'UNIT_IS_ATTACKING_REQUIREMENTS'),

-----   SIEGE   -----
		('BOMBARD_BONUS_VS_UNITS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'BOMBARD_BONUS_VS_UNITS_REQUIREMENTS'),

-----   ANTI CAVALRY   -----
		('HEAL_AFTER_ACTION', 'MODIFIER_PLAYER_UNIT_GRANT_HEAL_AFTER_ACTION', NULL),
		('CLOSE_RANKS_DEFENSE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'CREW_WEAPONS_REQUIREMENTS'),

-----   LIGHT CAVALRY   -----
		('EVASIVE_TARGET_DEFENSE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'CREW_WEAPONS_REQUIREMENTS'),
		('DOUBLE_ENVELOPMENT_ATTACK_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'UNIT_IS_ATTACKING_REQUIREMENTS'),

-----   HEAVY CAVALRY   -----
		('URBAN_ASSAULT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'URBAN_RAIDER_REQUIREMENTS'),
		('BARDING_DEFENSE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'CREW_WEAPONS_REQUIREMENTS'),
		('RELENTLESS_STRENGTH_REDUCTION', 'MODIFIER_PLAYER_UNIT_ADJUST_STRENGTH_REDUCTION_FOR_DAMAGE_MODIFIER', NULL),

-----   NAVAL MELEE   -----
		('REINFORCED_HULL_DEFENSE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'CREW_WEAPONS_REQUIREMENTS'),

-----   NAVAL RANGED   -----

-----   NAVAL RAIDER   -----
		('HEAL_FROM_COMBAT', 'MODIFIER_PLAYER_UNIT_ADJUST_HEAL_FROM_COMBAT', NULL),
		('PREDATOR_BONUS_VS_NAVAL', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'HOMING_TORPEDOES_REQUIREMENTS'),

-----   NAVAL CARRIER   -----
		('SUPER_CARRIER_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('MISSILE_ARRAY_ATTACK_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'UNIT_IS_ATTACKING_REQUIREMENTS'),
		('COMPARTMENTED_HULL_DEFENSE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'CREW_WEAPONS_REQUIREMENTS'),

-----   AIR FIGHTER   -----
		('TANK_BUSTER_BONUS_VS_DISTRICTS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'URBAN_RAIDER_REQUIREMENTS'),

-----   AIR BOMBER   -----


-----   MONK   -----
		('DISCIPLES_FAITH_FROM_COMBAT', 'MODIFIER_UNIT_ADJUST_POST_COMBAT_YIELD', NULL),
		('ZEALOTS_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'REQUIREMENTS_OPPONENT_IS_OTHER_RELIGION'),
		('IRON_FISTS_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('EXPLODING_PALMS_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('DANCING_CRANE_DEFENSE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'CREW_WEAPONS_REQUIREMENTS'),
		('DANCING_CRANE_IGNORE_ZOC', 'MODIFIER_PLAYER_UNIT_ADJUST_IGNORE_ZOC', NULL),
		('SHADOW_STRIKE_ATTACK_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'UNIT_IS_ATTACKING_REQUIREMENTS'),

-----   APOSTLE   -----
		('APOSTLE_COMBAT_BOOST', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('APOSTLE_SPREAD_CHARGE', 'MODIFIER_PLAYER_UNIT_ADJUST_SPREAD_CHARGES', NULL),

-----   AMBUSH   -----
		('AMBUSH_1_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('AMBUSH_2_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('AMBUSH_3_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('AMBUSH_4_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),

-----   VETERAN   -----
		('VETERAN_1_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('VETERAN_2_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('VETERAN_3_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('VETERAN_4_COMBAT_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),

-----   INCREASE HEAL RATE   -----
		('INCREASE_HEAL_RATE_5', 'MODIFIER_PLAYER_UNIT_ADJUST_HEAL_PER_TURN', NULL),
		('INCREASE_HEAL_RATE_10', 'MODIFIER_PLAYER_UNIT_ADJUST_HEAL_PER_TURN', NULL),
		('INCREASE_HEAL_RATE_15', 'MODIFIER_PLAYER_UNIT_ADJUST_HEAL_PER_TURN', NULL);



INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
-----   RECON   -----
		('SENTRY_COMBAT_BONUS', 'Amount', 7),
		('AQUATIC_BONUS_SEA_MOVEMENT', 'Amount', 2),
		('ALPINE_SEE_THROUGH_TERRAIN', 'CanSee', 1),

-----   MELEE   -----
		('AMPHIBIOUS_BONUS_SEA_MOVEMENT', 'Amount', 1),
		('URBAN_WARFARE_BONUS', 'Amount', 9),
		('TORTOISE_DEFENSE_BONUS', 'Amount', 7),
		('BATTLECRY_ATTACK_BONUS', 'Amount', 5),

-----   RANGED   -----
		('INCENDIARIES_BONUS_VS_DISTRICT_DEFENSES', 'Amount', 9),
		('GARRISON_BONUS_DISTRICTS', 'Amount', 9),
		('SIDE_ARMS_DEFENSE_BONUS', 'Amount', 7),
		('VOLLEY_ATTACK_BONUS', 'Amount', 5),

-----   SIEGE   -----
		('BOMBARD_BONUS_VS_UNITS', 'Amount', 7),
		('CREW_WEAPONS_DEFENSE_BONUS', 'Amount', 7),
		('SHELLS_BONUS_VS_DISTRICTS', 'Amount', 7),

-----   ANTI CAVALRY   -----
		('ECHELON_ADDITIONAL_CAVALRY_BONUS', 'Amount', 7),
		('CLOSE_RANKS_DEFENSE_BONUS', 'Amount', 7),

-----   LIGHT CAVALRY   -----
		('COURSERS_BONUS_VS_RANGED_SIEGE', 'Amount', 9),
		('EVASIVE_TARGET_DEFENSE_BONUS', 'Amount', 7),
		('DOUBLE_ENVELOPMENT_ATTACK_BONUS', 'Amount', 5),

-----   HEAVY CAVALRY   -----
		('URBAN_ASSAULT_BONUS', 'Amount', 9),
		('BARDING_DEFENSE_BONUS', 'Amount', 7),
		('RELENTLESS_STRENGTH_REDUCTION', 'Amount', 70),

-----   NAVAL MELEE   -----
		('REINFORCED_HULL_DEFENSE_BONUS', 'Amount', 7),
		('EMBOLON_BONUS_VS_NAVAL', 'Amount', 5),

-----   NAVAL RANGED   -----

-----   NAVAL RAIDER   -----
		('HEAL_FROM_COMBAT', 'Amount', 25),
		('PREDATOR_BONUS_VS_NAVAL', 'Amount', 5),

-----   NAVAL CARRIER   -----
		('SUPER_CARRIER_COMBAT_BONUS', 'Amount', 10),
		('MISSILE_ARRAY_ATTACK_BONUS', 'Amount', 7),
		('COMPARTMENTED_HULL_DEFENSE_BONUS', 'Amount', 7),

-----   AIR FIGHTER   -----
		('TANK_BUSTER_BONUS_VS_CAVALRY', 'Amount', 7),
		('TANK_BUSTER_BONUS_VS_DISTRICTS', 'Amount', 7),
		('STRAFE_BONUS_VS_NONCAVALRY', 'Amount', 7),

-----   AIR BOMBER   -----
		('TORPEDO_BOMBER_BONUS_VS_NAVAL', 'Amount', 10),
		('CLOSE_AIR_SUPPORT_BONUS_VS_LAND', 'Amount', 7),

-----   MONK   -----
		('DISCIPLES_FAITH_FROM_COMBAT', 'PercentDefeatedStrength', 50),
		('DISCIPLES_FAITH_FROM_COMBAT', 'YieldType', 'YIELD_FAITH'),
		('ZEALOTS_COMBAT_BONUS', 'Amount', 10),
		('IRON_FISTS_COMBAT_BONUS', 'Amount', 5),
		('EXPLODING_PALMS_COMBAT_BONUS', 'Amount', 7),
		('DANCING_CRANE_DEFENSE_BONUS', 'Amount', 5),
		('DANCING_CRANE_IGNORE_ZOC', 'Ignore', 1),
		('SHADOW_STRIKE_ATTACK_BONUS', 'Amount', 5),

-----   APOSTLE   -----
		('APOSTLE_COMBAT_BOOST', 'Amount', 10),
		('APOSTLE_SPREAD_CHARGE', 'Amount', 1),

-----   AMBUSH   -----
		('AMBUSH_1_COMBAT_BONUS', 'Amount', 5),
		('AMBUSH_2_COMBAT_BONUS', 'Amount', 5),
		('AMBUSH_3_COMBAT_BONUS', 'Amount', 5),
		('AMBUSH_4_COMBAT_BONUS', 'Amount', 5),

-----   VETERAN   -----
		('VETERAN_1_COMBAT_BONUS', 'Amount', 3),
		('VETERAN_2_COMBAT_BONUS', 'Amount', 3),
		('VETERAN_3_COMBAT_BONUS', 'Amount', 3),
		('VETERAN_4_COMBAT_BONUS', 'Amount', 3),

-----   INCREASE HEAL RATE   -----
		('INCREASE_HEAL_RATE_5', 'Amount', 5),
		('INCREASE_HEAL_RATE_10', 'Amount', 10),
		('INCREASE_HEAL_RATE_15', 'Amount', 15);



INSERT OR REPLACE INTO ModifierStrings (ModifierId, Context, Text) VALUES 
-----   RECON   -----
		('SENTRY_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_SENTRY_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   MELEE   -----
		('TORTOISE_DEFENSE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_TORTOISE_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('BATTLECRY_ATTACK_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_BATTLECRY_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   RANGED   -----
		('SIDE_ARMS_DEFENSE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_SIDE_ARMS_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('VOLLEY_ATTACK_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_VOLLEY_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   SIEGE   -----
		('BOMBARD_BONUS_VS_UNITS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_SHRAPNEL_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   ANTI CAVALRY   -----
		('CLOSE_RANKS_DEFENSE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_CLOSE_RANKS_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   LIGHT CAVALRY   -----
		('EVASIVE_TARGET_DEFENSE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_EVASIVE_TARGET_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('DOUBLE_ENVELOPMENT_ATTACK_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_DOUBLE_ENVELOPMENT_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   HEAVY CAVALRY   -----
		('URBAN_ASSAULT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_URBAN_ASSAULT_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('BARDING_DEFENSE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_BARDING_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   NAVAL MELEE   -----
		('REINFORCED_HULL_DEFENSE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_REINFORCED_HULL_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   NAVAL RANGED   -----

-----   NAVAL RAIDER   -----
		('PREDATOR_BONUS_VS_NAVAL', 'Preview', '+{1_Amount}  {LOC_PROMOTION_PREDATOR_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   NAVAL CARRIER   -----
		('SUPER_CARRIER_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_SUPER_CARRIER_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('MISSILE_ARRAY_ATTACK_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_MISSILE_ARRAY_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('COMPARTMENTED_HULL_DEFENSE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_COMPARTMENTED_HULL_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   AIR FIGHTER   -----
		('TANK_BUSTER_BONUS_VS_DISTRICTS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_TANK_BUSTER_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   AIR BOMBER   -----

-----   MONK   -----
		('ZEALOTS_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_MONK_ZEALOTS_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('IRON_FISTS_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_MONK_IRON_FISTS_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('EXPLODING_PALMS_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_MONK_EXPLODING_PALMS_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('DANCING_CRANE_DEFENSE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_MONK_DANCING_CRANE_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('SHADOW_STRIKE_ATTACK_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_MONK_SHADOW_STRIKE_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   APOSTLE   -----
		('APOSTLE_COMBAT_BOOST', 'Preview', '+{1_Amount}  {LOC_PROMOTION_EXEMPLAR_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   AMBUSH   -----
		('AMBUSH_1_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_AMBUSH_1_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('AMBUSH_2_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_AMBUSH_2_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('AMBUSH_3_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_AMBUSH_3_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('AMBUSH_4_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_AMBUSH_4_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),

-----   VETERAN   -----
		('VETERAN_1_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_VETERAN_1_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('VETERAN_2_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_VETERAN_2_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('VETERAN_3_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_VETERAN_3_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('VETERAN_4_COMBAT_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_VETERAN_4_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}');



--  New Requirements
INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
		('UNIT_IS_ATTACKING_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
		('UNIT_IS_ON_WATER_REQUIREMENTS', 'REQUIREMENTSET_TEST_ANY'),
		('BOMBARD_BONUS_VS_UNITS_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
		('SENTRY_COMBAT_REQUIREMENTS', 'REQUIREMENTSET_TEST_ANY');

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
		('UNIT_IS_ATTACKING_REQUIREMENTS', 'PLAYER_IS_ATTACKER_REQUIREMENTS'),
		('UNIT_IS_ON_WATER_REQUIREMENTS', 'REQUIRES_PLOT_IS_LAKE'),
		('UNIT_IS_ON_WATER_REQUIREMENTS', 'REQUIRES_PLOT_IS_COAST'),
		('UNIT_IS_ON_WATER_REQUIREMENTS', 'REQUIRES_PLOT_IS_OCEAN'),
		('BOMBARD_BONUS_VS_UNITS_REQUIREMENTS', 'PLAYER_IS_ATTACKER_REQUIREMENTS'),
		('BOMBARD_BONUS_VS_UNITS_REQUIREMENTS', 'OPPONENT_IS_NOT_DISTRICT'),
		('SENTRY_COMBAT_REQUIREMENTS', 'PLAYER_IS_DEFENDER_REQUIREMENTS'),
		('SENTRY_COMBAT_REQUIREMENTS', 'GARRISON_PLOT_REQUIREMENTS_MET');

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType, Inverse) VALUES 
		('REQUIRES_PLOT_IS_OCEAN', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES', 0),
		('OPPONENT_IS_NOT_DISTRICT', 'REQUIREMENT_OPPONENT_IS_DISTRICT', 1);

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value) VALUES 
		('REQUIRES_PLOT_IS_OCEAN', 'TerrainType', 'TERRAIN_OCEAN');


--  New ModifierType
INSERT OR REPLACE INTO Types (Type, Kind) VALUES 
		('MODIFIER_PLAYER_UNIT_ADJUST_STRENGTH_REDUCTION_FOR_DAMAGE_MODIFIER', 'KIND_MODIFIER');
		
INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES 
		('MODIFIER_PLAYER_UNIT_ADJUST_STRENGTH_REDUCTION_FOR_DAMAGE_MODIFIER', 'COLLECTION_OWNER', 'EFFECT_ADJUST_UNIT_STRENGTH_REDUCTION_FOR_DAMAGE_MODIFIER');





-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--  Compatibility for DLC
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Add class if not already present
INSERT INTO Types (Type, Kind) SELECT 'PROMOTION_CLASS_NIHANG', 'KIND_PROMOTION_CLASS' WHERE NOT EXISTS (SELECT 1 FROM Types WHERE Type = 'PROMOTION_CLASS_NIHANG');

INSERT INTO UnitPromotionClasses (PromotionClassType, Name) SELECT 'PROMOTION_CLASS_NIHANG', 'LOC_PROMOTION_CLASS_NIHANG_NAME' WHERE NOT EXISTS (SELECT 1 FROM UnitPromotionClasses WHERE PromotionClassType = 'PROMOTION_CLASS_NIHANG');


-- Remove original promotions
UPDATE UnitPromotions SET PromotionClass='PROMOTION_CLASS_HIDDEN' WHERE PromotionClass='PROMOTION_CLASS_NIHANG';



--  Create new promotions
INSERT OR REPLACE INTO Types (Type, Kind) VALUES 
-----   NIHANG   -----
		('PROMOTION_NIHANG_1', 'KIND_PROMOTION'),
		('PROMOTION_NIHANG_2', 'KIND_PROMOTION'),
		('PROMOTION_NIHANG_3', 'KIND_PROMOTION'),
		('PROMOTION_NIHANG_4', 'KIND_PROMOTION'),
		('PROMOTION_NIHANG_5', 'KIND_PROMOTION'),
		('PROMOTION_NIHANG_6', 'KIND_PROMOTION'),
		('PROMOTION_NIHANG_7', 'KIND_PROMOTION'),
		('PROMOTION_NIHANG_8', 'KIND_PROMOTION');

INSERT OR REPLACE INTO UnitPromotions (UnitPromotionType, Name, Description, Level, Column, PromotionClass) VALUES 
-----   NIHANG   -----
		('PROMOTION_NIHANG_4', 'LOC_PROMOTION_NIHANG_ELITE_NAME', 'LOC_PROMOTION_NIHANG_ELITE_DESCRIPTION', 1, 1, 'PROMOTION_CLASS_NIHANG'),
		('PROMOTION_NIHANG_3', 'LOC_PROMOTION_VETERAN_3_NAME', 'LOC_PROMOTION_VETERAN_3_DESCRIPTION', 2, 1, 'PROMOTION_CLASS_NIHANG'),
		('PROMOTION_NIHANG_2', 'LOC_PROMOTION_VETERAN_2_NAME', 'LOC_PROMOTION_VETERAN_2_DESCRIPTION', 3, 1, 'PROMOTION_CLASS_NIHANG'),
		('PROMOTION_NIHANG_1', 'LOC_PROMOTION_VETERAN_1_NAME', 'LOC_PROMOTION_VETERAN_1_DESCRIPTION', 4, 1, 'PROMOTION_CLASS_NIHANG'),

		('PROMOTION_NIHANG_8', 'LOC_PROMOTION_NIHANG_ATTACK_NAME', 'LOC_PROMOTION_NIHANG_ATTACK_DESCRIPTION', 1, 3, 'PROMOTION_CLASS_NIHANG'),
		('PROMOTION_NIHANG_7', 'LOC_PROMOTION_NIHANG_MOVEMENT_NAME', 'LOC_PROMOTION_NIHANG_MOVEMENT_DESCRIPTION', 2, 3, 'PROMOTION_CLASS_NIHANG'),
		('PROMOTION_NIHANG_6', 'LOC_PROMOTION_NIHANG_FAITH_NAME', 'LOC_PROMOTION_NIHANG_FAITH_DESCRIPTION', 3, 3, 'PROMOTION_CLASS_NIHANG'),
		('PROMOTION_NIHANG_5', 'LOC_PROMOTION_NIHANG_RELENTLESS_NAME', 'LOC_PROMOTION_RELENTLESS_DESCRIPTION', 4, 3, 'PROMOTION_CLASS_NIHANG');

INSERT OR REPLACE INTO UnitPromotionModifiers (UnitPromotionType, ModifierId) VALUES 
-----   NIHANG   -----
		('PROMOTION_NIHANG_4', 'NIHANG_ELITE_BONUS'),
		('PROMOTION_NIHANG_3', 'VETERAN_3_COMBAT_BONUS'),
		('PROMOTION_NIHANG_2', 'VETERAN_2_COMBAT_BONUS'),
		('PROMOTION_NIHANG_1', 'VETERAN_1_COMBAT_BONUS'),

		('PROMOTION_NIHANG_8', 'NIHANG_ATTACK_BONUS'),
		('PROMOTION_NIHANG_7', 'DANCING_CRANE_BONUS_MOVEMENT'),
		('PROMOTION_NIHANG_6', 'DISCIPLES_FAITH_FROM_COMBAT'),
		('PROMOTION_NIHANG_5', 'RELENTLESS_STRENGTH_REDUCTION');

INSERT OR REPLACE INTO UnitPromotionPrereqs (UnitPromotion, PrereqUnitPromotion) VALUES 
-----   NIHANG   -----
		('PROMOTION_NIHANG_2', 'PROMOTION_NIHANG_1'),
		('PROMOTION_NIHANG_3', 'PROMOTION_NIHANG_2'),
		('PROMOTION_NIHANG_4', 'PROMOTION_NIHANG_3');


INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 
-----   NIHANG   -----
		('NIHANG_ELITE_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL),
		('NIHANG_ATTACK_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'UNIT_IS_ATTACKING_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
-----   NIHANG   -----
		('NIHANG_ELITE_BONUS', 'Amount', 6),
		('NIHANG_ATTACK_BONUS', 'Amount', 5);

INSERT OR REPLACE INTO ModifierStrings (ModifierId, Context, Text) VALUES 
-----   NIHANG   -----
		('NIHANG_ELITE_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_NIHANG_ELITE_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}'),
		('NIHANG_ATTACK_BONUS', 'Preview', '+{1_Amount}  {LOC_PROMOTION_NIHANG_ATTACK_NAME}  {LOC_PROMOTION_DESCRIPTOR_PREVIEW_TEXT}');



-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--  Compatibility for "Warfare Expanded: Reloaded"
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
